// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.keyboardevent.keypress.hack.use_legacy_keycode_and_charcode", "powerpoint.officeapps.live.com");
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "d37ac9a4-d654-4b81-a617-35f43bebd8ab");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1553508611);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1553508731);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1553509091);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1553509331);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1553509211);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1551884620);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1553508971);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1553508851);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1551884230);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5609348e-6bbd-4149-aa55-dcbcfd3cfcaf}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1551999600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1553512198498");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1553514001498");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1553512187173");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1553515787173");
user_pref("browser.search.region", "BA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190315140653");
user_pref("browser.slowStartup.averageTime", 1808);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190315140653");
user_pref("browser.startup.homepage_override.mstone", "66.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1551884231772");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "15df8de996e64dad8a3d2fa42fbae529");
user_pref("extensions.blocklist.lastModified", "Thu, 21 Mar 2019 12:41:01 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1553508614);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001155");
user_pref("extensions.lastAppVersion", "66.0");
user_pref("extensions.lastPlatformVersion", "66.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{ebf48e7e-564c-4c65-aa26-115f00d41de4}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4cb8a868-9d0b-40d9-9d00-62660cc87a2e\",\"screenshots@mozilla.org\":\"6d36576f-446a-402f-92db-840ac3ed6508\",\"webcompat-reporter@mozilla.org\":\"af10f6c6-22e5-4fd8-a142-aaee8f2f4a9b\",\"webcompat@mozilla.org\":\"4487babb-33b5-4c17-bc10-39d2dc9fa443\",\"fxmonitor@mozilla.org\":\"c5e2ed4e-52f4-4da1-b19d-32b3353b41e2\"}");
user_pref("idle.lastDailyNotification", 1553511229);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1551884594);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190315140653");
user_pref("media.gmp-manager.lastCheck", 1553508617);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1553511229);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.sandbox.content.tempDirSuffix", "6494cdc0-5679-4074-bc8b-75508a4704c2");
user_pref("security.sandbox.plugin.tempDirSuffix", "14ae7a42-65a3-4279-9f0c-f40d34e1de3c");
user_pref("services.blocklist.addons.checked", 1553508594);
user_pref("services.blocklist.gfx.checked", 1553508594);
user_pref("services.blocklist.onecrl.checked", 1553508594);
user_pref("services.blocklist.pinning.checked", 1553508594);
user_pref("services.blocklist.plugins.checked", 1553508594);
user_pref("services.settings.clock_skew_seconds", -12);
user_pref("services.settings.last_update_seconds", 1553508594);
user_pref("services.settings.main.language-dictionaries.last_check", 1553508594);
user_pref("services.settings.main.onboarding.last_check", 1553508594);
user_pref("services.settings.main.sites-classification.last_check", 1553508594);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1553511229);
user_pref("toolkit.startup.last_success", 1553508579);
user_pref("toolkit.telemetry.cachedClientID", "8bd790be-2681-4196-bf6a-c6ab5361a860");
user_pref("toolkit.telemetry.previousBuildID", "20190315140653");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
